//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic_Books_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int stock { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public int subcategory_id { get; set; }
        public Nullable<int> isbn { get; set; }
        public Nullable<int> total_pages { get; set; }
        public Nullable<System.DateTime> published_date { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public int category_id { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
