//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic_Books_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_cart
    {
        public int shopping_cart_id { get; set; }
        public int product_id { get; set; }
        public string order_status { get; set; }
        public decimal grand_total { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
